[package]
name = "embex"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.8"
tokio = { version = "1.42.0", features = ["full"] }
