services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: ghcr.io/excoffierleonard/embex
    container_name: embex-app
    networks:
      - embex
  
  db:
    image: ankane/pgvector # Need to implement more secure option later
    container_name: embex-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - embex

networks:
  embex:
    name: embex